version = 0.1
[default.deploy.parameters]
stack_name = "sam-appV2"
resolve_s3 = true
s3_prefix = "sam-appV2"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
